### ISSUE TITLE
Error in optim(para, ...) : L-BFGS-B needs finite values of 'fn'

### ISSUE THREAD

**Issue by arzwa** [cecileane/WGDgc#1]
Hi, 

I've used WGDgc successfully in the past, however I have some unexpected errors currently. 
Consider the following species tree in `simmap` format (read into variable `tre.phylo4d`):

```
 ((MPOL:{0,4.9058224222},PPAT:{0,4.9058224222}):{0,0.4170966978},(SMOE:{0,4.3125139636},(((OSAT:{0,1.6047712725},(ATHA:{0,0.6820000000},CPAP:{0,0.6820000000}):{0,0.9227712725}):{0,0.2040857832},ATRI:{0,1.8088570558}):{0,1.3184042224},(GBIL:{0,2.9556845545},    (PABI:{0,1.1574835000},PTAE:{0,1.1574835000}):{0,1.7982010545}):{0,0.1715767236}):{0,1.1852526855}):{0,1.0104051564});
```
and this test data set (`test`):

```
   OSAT ATHA GBIL ATRI PABI PPAT CPAP MPOL PTAE SMOE
1     9    7    8   10    8    2    8    3   11    2
2     0    0    0    0   12    8    0    0    7    1
3     6    9    1    5    2    2    7    1    1    0
4     0    0    1    0    1    1    0    2    2    0
5     5    4    3    3    5    2    4    2    2    0
6     0    0    4    0    7    1    0    2   13    0
7     4    3    1    2    0    3    1    1    0    0
8     8    8    5    7   17   11   11    2   16    2
9     2    4    2    2    8    3    5    1   13    1
10    1    0    1    0    5    0    0    1    4    0
```
Running WGDgc as follows 
```R
wgdgc_out = MLEGeneCount(tre.phylo4d, test, geomMean=1.5, conditioning="oneInBothClades", fixedRetentionRates=TRUE)
```
The following error occurs `Error in optim(para, getLikGeneCount, input = input, geneCountData = geneCountData,  :   L-BFGS-B needs finite values of 'fn'`. So it seems the likelihood evaluates to some infinite value during optimization. Since this test data set seems not to violate any assumption (there is at least one gene in both clades stemming from the root, all taxa in the data set match taxa in the tree, the counts are all finite and not extraordinary) and the same error occurs for other conditioning schemes, it seems to me there could be a bug,  or am I missing something?

Thanks, 
Arthur

**Comment by cecileane** [comment]
It looks like a convergence issue that can be avoided by choosing better starting values for the background duplication & loss rates. To avoid the convergence issue, I used the option `equalBDrates=TRUE` to assume equal rates of duplications & losses. It makes the model simpler, and therefore easier to optimize. I didn't get any error when using this assumption 👍  so yes you are correct: there is nothing wrong with the tree or with the data. The problem is that the optimization goes into areas where parameter values are too high or too low and end up making the likelihood infinite. Assuming equal rates, I got an estimate of 0.354 for λ=μ. So I re-ran the estimation using starting values for λ and μ that were both close to 0.354, but letting them be different with `equalBDrates=FALSE` (the default). And this time, the optimization converged without error. Code below.

```r
library(ape)
library(WGDgc)
test = read.csv("arthurZwaenepoel.csv") # file made using your screen output above
tre.phylo4d = read.simmap(text="((MPOL:{0,4.9058224222},PPAT:{0,4.9058224222}):{0,0.4170966978},(SMOE:{0,4.3125139636},(((OSAT:{0,1.6047712725},(ATHA:{0,0.6820000000},CPAP:{0,0.6820000000}):{0,0.9227712725}):{0,0.2040857832},ATRI:{0,1.8088570558}):{0,1.3184042224},(GBIL:{0,2.9556845545},(PABI:{0,1.1574835000},PTAE:{0,1.1574835000}):{0,1.7982010545}):{0,0.1715767236}):{0,1.1852526855}):{0,1.0104051564});")
tre.phylo4d # no apparent problem
plot(collapse.singles(as(tre.phylo4d, "phylo"))) # just to see what is the outgroup / in-group
wgdgc_out = MLEGeneCount(tre.phylo4d, test, geomMean=1.5, conditioning="oneInBothClades", fixedRetentionRates=TRUE,
    equalBDrates=TRUE) # default startingBDrates=c(.01, .02), first one used if equal rates
# no error :)
wgdgc_out$birthrate # 0.354447: 35 times higher than the default starting value
wgdgc_out = MLEGeneCount(tre.phylo4d, test, geomMean=1.5, conditioning="oneInBothClades", fixedRetentionRates=TRUE,
    equalBDrates=FALSE, startingBDrates=c(0.354447,0.36))
# no error :)
wgdgc_out$birthrate # 0.3386061
wgdgc_out$deathrate # 0.2609594
```

**Comment by arzwa** [comment]
I see, thanks a lot for the clarification!
