### ISSUE TITLE
question about MLEGeneCount and tree format

### ISSUE THREAD

**Issue by wuxiaopei0509** [cecileane/WGDgc#3]
Hello,
I want to use the WGDgc package to estimate the root prior, namely the mean of a geometric distribution. Then I use the MLEGeneCount  function, the Rscript is:MLEGeneCount(tr, geneCountData, mMax=NULL, geomMean=TRUE, conditioning=c("oneOrMore"),equalBDrates=FALSE, fixedRetentionRates=TRUE,startingBDrates=c(0.01, 0.02),startingQ=NULL). Finally, I get the BD value ,however the  geom  value couldnot show. Another question, in the manul, it said, Along a given branch, the token "0,18" indicates state 0 for a durationof 18 time units. Does it mean the branch length in time unit and how can I get the branch length in time unit?

**Comment by cecileane** [comment]
- `geomMean` should be a value of your choice, and should be 1 or higher. You used `geomMean=TRUE`, which should be equivalent to `geomMean=1` because in a numerical context, R interprets true as 1. For example, `1/TRUE` returns 1 in R.

- Yes correct, 18 would be the length of the branch, in your example. This branch length is something that you need to set yourself. It is not estimated by `MLEGeneCount`. We would typically estimate branch lengths using a multiple alignments of orthologous genes, at the same time as the species tree is estimated.

**Comment by wuxiaopei0509** [comment]
Thank you for your rapid reply, I got it.

















At 2020-10-21 10:04:00, "Cécile Ané" <notifications@github.com> wrote:

geomMean should be a value of your choice, and should be 1 or higher. You used geomMean=TRUE, which should be equivalent to geomMean=1 because in a numerical context, R interprets true as 1. For example, 1/TRUE returns 1 in R.

Yes correct, 18 would be the length of the branch, in your example. This branch length is something that you need to set yourself. It is not estimated by MLEGeneCount. We would typically estimate branch lengths using a multiple alignments of orthologous genes, at the same time as the species tree is estimated.
